
language: python
python:
  - "2.7"
  - "3.6"
sudo: required
cache: pip
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-format-6.0
    - rabbitmq-server
    - jq
    - curl

services:
  - docker
  - rabbitmq
  - redis

git:
  submodules: false

# This script is triggered only with python2.7 (as below python3.6 is excluded from the matrix)
before_install:
  - sudo apt update && sudo apt install -y protobuf-compiler
  - sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
  - git submodule update --init --recursive

before_script:
  - pip install -r source/tyr/requirements_dev.txt
  - bash source/scripts/build_protobuf.sh

script:
  - bash source/scripts/check_submodules.sh
  - pushd source/tyr && PYTHONPATH=.:../navitiacommon/ py.test --doctest-modules --ignore=migrations/ && popd

matrix:
  include:  # This script is triggered only with python3.6
    - python: "3.6"
      before_script:
        - pip install -r requirements_pre-commit.txt
        - pip install pre-commit
        - pre-commit install
        - bash source/scripts/build_protobuf.sh
      script:
        - pre-commit run --all --show-diff-on-failure
        - ./source/scripts/checkJenkinsJob.sh Artemis 
        - ./source/scripts/checkJenkinsJob.sh Artemis_idfm
  exclude:
    - python: "3.6"
