
language: cpp

git:
  submodules: false

before_install:
  - sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
  - git submodule update --init --recursive

script:
  - bash source/scripts/check_submodules.sh # Make sure submodules references are merged in !
