name: Build Navitia Packages For Release

on:
  pull_request:
  push:
    branches:
      - release


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            distribution: [debian8, debian9, debian10]

    container:
      image: navitia/${{matrix.distribution}}_dev

    steps:
    - uses: actions/checkout@v1
    - name: install zip dependency
      run: apt update && apt install -y zip httpie
    - name: dkpg-buildpackage
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
        DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b
    - name: create navitia_${{matrix.distribution}}_packages.zip
      run: |
        zip navitia_${{matrix.distribution}}_packages.zip ../navitia-*
    - name: upload ${{matrix.distribution}} packages
      uses: actions/upload-artifact@v1
      with:
        name: navitia-${{matrix.distribution}}-packages
        path: "navitia_${{matrix.distribution}}_packages.zip"
    - name: remove useless temporary files
      run: rm -rf ../navitia-*

    #- name: trigger jenkins to publish Artifacts on internal server
      #run: http --ignore-stdin -v -f POST https://${{secrets.JENKINS_NG_TOKEN}}@jenkins-core.canaltp.fr/job/publish-navitia-packages/buildWithParameters PLATFORM=navitia_debian8_packages
    - name: slack notification (the job has failed)
      if: failure()
      run: |
          echo '{"text":":warning: Github Actions: build_navitia_packages_for_release failed ! (https://github.com/CanalTP/navitia/actions?query=workflow%3A%22Build+Navitia+Packages+For+Release%22). Navboys, this is a release alert !!!"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}

    - name: slack notification (the job has successed)
      if: success() && matrix.distribution == 'debian8'
      run: |
          echo ${{matrix.distribution}}
          #version_number=$(head -n 1 debian/changelog | cut -d'(' -f 2 | cut -d')' -f 1)
          #echo '{"text":":information_source: Github Actions: build_navitia_packages_for_release succeded -' $version_number 'navitia debian packages are available"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}
          #echo '{"text":":octopus: Navitia Release: The version' $version_number 'is available. changelog: https://github.com/CanalTP/navitia/releases/tag/v'$version_number'"}' | http --json POST ${{secrets.SLACK_NAVITIA_URL}}
