name: Build Navitia Packages For Dev Multi Distributions

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            distribution: [debian8, debian10, debian11]

    container:
      image: navitia/${{matrix.distribution}}_dev
      volumes:
          - /usr/share/dotnet:/usr/share/dotnet
          - /usr/local/lib/android:/usr/local/lib/android
        # Mount /dotnet so we can delete files from docker and free up space (>20GB)

    steps:
    - name: Free up space
      run: |
        rm -rf /usr/share/dotnet/*
        rm -rf /usr/local/lib/android/*
        echo "Free space:"
        df -h
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install zip dependency
      run: apt update && apt install -y --force-yes zip httpie dh-python
    - name: Restore ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{matrix.distribution}}-package
        max-size: 2000M
        save: ${{ github.event_name == 'push' }}
    - name: dkpg-buildpackage
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
        DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b
    - name: create navitia_${{matrix.distribution}}_packages.zip
      run: |
        zip navitia_${{matrix.distribution}}_packages.zip ../navitia-* ../mock-kraken*
    - name: upload ${{matrix.distribution}} packages
      uses: actions/upload-artifact@v3
      with:
        name: navitia-${{matrix.distribution}}-packages
        path: "navitia_${{matrix.distribution}}_packages.zip"
    - name: remove useless temporary files
      run: rm -rf ../navitia-*
    - name: slack notification (the job has failed)
      if: failure() && github.event_name == 'push'
      run: |
          echo '{"text":":warning: Navitia Github Actions: build_navitia_${{matrix.distribution}}_packages_for_dev failed (https://github.com/hove-io/navitia/actions?query=workflow%3A%22Build+Navitia+Packages+For+Dev+Multi+Distributions%22)"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}


  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - uses: actions/checkout@v3
      with:
        repository: hove-io/navitia-docker-compose
    - name: install httpie dependency
      run: sudo apt update && sudo apt install -y httpie
    - uses: actions/download-artifact@v3 # Download all artifacts Debian8 (job 'build') to the current working directory
      with:
        name: navitia-debian8-packages
        path: ./builder_from_package
    - name: build, create and publish images for branch dev
      if: ${{ github.event_name == 'push' }}
      working-directory: builder_from_package
      run: ./build.sh -o ${{secrets.access_token_github}} -d debian8 -n -e push -t dev -b dev -r -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
    - name: build and create images for pull_request
      if: ${{ github.event_name != 'push' }}
      working-directory: builder_from_package
      run: ./build.sh -o ${{secrets.access_token_github}} -d debian8 -n -e push -t dev -b dev
    - name: slack notification (the job has failed)
      if: ${{ failure() && github.event_name == 'push' }}
      run: |
          echo '{"text":":warning: Navitia Github Actions: publish_docker_compose_images failed ! "}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}

  artemis:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: run artemis  on push to dev
      if: ${{ github.event_name == 'push' }}
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.access_token_github }}
        repository: hove-io/artemis
        event-type: run_artemis_ng
