name: Build Navitia Packages For Dev Multi Distributions

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            distribution: [debian8, debian10, debian11]

    container:
      image: navitia/${{matrix.distribution}}_dev
      volumes:
          - /usr/share/dotnet:/usr/share/dotnet
          - /usr/local/lib/android:/usr/local/lib/android
        # Mount /dotnet so we can delete files from docker and free up space (>20GB)

    steps:
    - name: Free up space
      run: |
        rm -rf /usr/share/dotnet/*
        rm -rf /usr/local/lib/android/*
        echo "Free space:"
        df -h
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install zip dependency
      run: apt update && apt install -y zip httpie dh-python
    - name: Restore ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{matrix.distribution}}-package
        max-size: 2000M
    - name: dkpg-buildpackage
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
        DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b
    - name: create navitia_${{matrix.distribution}}_packages.zip
      run: |
        zip navitia_${{matrix.distribution}}_packages.zip ../navitia-* ../mock-kraken*
    - name: upload ${{matrix.distribution}} packages
      uses: actions/upload-artifact@v3
      with:
        name: navitia-${{matrix.distribution}}-packages
        path: "navitia_${{matrix.distribution}}_packages.zip"
    - name: remove useless temporary files
      run: rm -rf ../navitia-*
    - name: slack notification (the job has failed)
      if: failure() && github.event_name == 'push'
      run: |
          echo '{"text":":warning: Navitia Github Actions: build_navitia_${{matrix.distribution}}_packages_for_dev failed (https://github.com/hove-io/navitia/actions?query=workflow%3A%22Build+Navitia+Packages+For+Dev+Multi+Distributions%22)"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}


  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - uses: actions/checkout@v3
      with:
        repository: hove-io/navitia-docker-compose
    - name: install httpie dependency
      run: sudo apt update && sudo apt install -y httpie
    - uses: actions/download-artifact@v3 # Download all artifacts Debian10 (job 'build') to the current working directory
      with:
        name: navitia-debian10-packages
        path: ./builder_from_package/debian10
    - name: build, create and publish images for branch dev
      if: ${{ github.event_name == 'push' }}
      working-directory: builder_from_package/debian10
      run: ./build.sh -o ${{secrets.access_token_github}} -n -r -e push -t dev -b dev -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
    - name: slack notification (the job has failed)
      if: failure()
      run: |
          echo '{"text":":warning: Navitia Github Actions: publish_docker_compose_images failed ! "}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}

  artemis:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: install dependency
      run: |
        sudo apt update && sudo apt install -y httpie
        pip3 install requests
    - name: run artemis NG on push
      shell: python3 {0}
      if: ${{ github.event_name == 'push' }}
      run: |
        import json
        import requests

        # replace \n, simple quotes and double quotes by spaces
        translation_table = str.maketrans({ '\n' : ' ', "'" : ' ', '"': ' ' })
        def sanitize(my_string):
          sanitized = my_string.translate(translation_table)
          return sanitized

        with open('${{ github.event_path }}') as file:

          github_dict = json.load(file)

          params = {}
          params["event"] = "push"
          params["navitia_branch"] = "dev"
          params["commit_message"] = sanitize(github_dict['head_commit']['message'])
          params["commit_timestamp"] = github_dict['head_commit']['timestamp']
          params["commit_url"] = github_dict['repository']['html_url']
          params["commit_id"] = github_dict['head_commit']['id']
          params["commit_username"] = github_dict['head_commit']['author']['name']

          secret = "${{secrets.JENKINS_NG_TOKEN}}"

          url = "https://{}@jenkins-core.canaltp.fr/job/artemis_ng/buildWithParameters".format(secret)
          request = requests.post(url, data = params )
          print("Response status code : {}".format(request.status_code) )
          print(request.text)

          url = "https://{}@jenkins-core.canaltp.fr/job/artemis_ng_debian8/buildWithParameters".format(secret)
          request = requests.post(url, data = params )
          print("Response status code : {}".format(request.status_code) )
          print(request.text)

    - name: run artemis NG on pull_request
      shell: python3 {0}
      if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run_artemis') }}
      run: |
        import json
        import requests

        # replace \n, simple quotes and double quotes by spaces
        translation_table = str.maketrans({ '\n' : ' ', "'" : ' ', '"': ' ' })
        def sanitize(my_string):
          sanitized = my_string.translate(translation_table)
          return sanitized

        with open('${{ github.event_path }}') as file:

          github_dict = json.load(file)
          params = {}
          params["event"] = "pull_request"
          params["navitia_branch"] = github_dict['pull_request']['head']['ref']
          params["commit_message"] = sanitize(github_dict['pull_request']['title'])
          params["commit_timestamp"] = github_dict['pull_request']['updated_at']
          params["commit_url"] = github_dict['pull_request']['html_url']
          params["commit_id"] = github_dict['pull_request']['head']['sha']
          params["commit_username"] = github_dict['pull_request']['user']['login']
          print(params)

          secret = "${{secrets.JENKINS_NG_TOKEN}}"

          url = "https://{}@jenkins-core.canaltp.fr/job/artemis_ng/buildWithParameters".format(secret)
          request = requests.post(url, data = params )
          print("Response status code : {}".format(request.status_code) )
          print(request.text)

          url = "https://{}@jenkins-core.canaltp.fr/job/artemis_ng_debian8/buildWithParameters".format(secret)
          request = requests.post(url, data = params )
          print("Response status code : {}".format(request.status_code) )
          print(request.text)
