name: Clang-tidy

on:
  push:
    branches:
    - _clang-tidy
    - _release
  pull_request:
    branches: [ dev ]

env:
  REGION: eu-west-1


jobs:
  aws_creds:
    name: Get ECR Access
    runs-on: [ self-hosted, corefront, sandbox ]
    outputs:
      token: ${{ steps.ecr_token.outputs.token }}
    steps:
      - id: ecr_token
        name: Get ECR Token
        run: |
          echo token=$(aws ecr get-login-password --region $REGION) >> $GITHUB_OUTPUT

  clang-tidy:
    runs-on: [self-hosted, corefront, sandbox]
    needs: aws_creds
    container:
      image: 162230498103.dkr.ecr.eu-west-1.amazonaws.com/mutable-debian11_dev:latest
      credentials:
        username: AWS
        password: ${{ needs.aws_creds.outputs.token }}
    steps:
    - name: Generate github private access token
      id: ci-core-app-token
      uses: getsentry/action-github-app-token@v2.0.0
      with:
        app_id: ${{ secrets.CI_CORE_APP_ID }}
        private_key: ${{ secrets.CI_CORE_APP_PEM }}
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ steps.ci-core-app-token.outputs.token }}
    - name : Install dependencies
      run: apt update && apt install -y clang-tools clang-tidy
    - name : Clang-tidy Info
      run: clang-tidy --version
    - name: cmake
      working-directory: ${{ runner.temp }}
      run: cmake $GITHUB_WORKSPACE/source
    - name: Clang-tidy
      working-directory: ${{ runner.temp }}
      run: make tidy_fix || echo "Files have been tidied ! Let's commit them"
#    - name: Commit and push changes
#      # Handle case with no clang-tidy fix
#      continue-on-error: true
#      uses: peter-evans/create-pull-request@v3
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        commit-message: Clang-tidy the code base
#        committer: GitHub <noreply@github.com>
#        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#        title: '[Clang-Tidy] Code maintenance and modernisation'
#        body: |
#          ðŸ¤– This is an automatic PR ðŸ¤–
#
#          Clang-tidy suggests the following changes so far:
#          - `clang-analyzer-*` : clang Static Analyzer checks.
#
#          [#clang-tidy documentation](https://clang.llvm.org/extra/clang-tidy/)
#        labels: not_in_changelog
#        team-reviewers: hove-io/coreteam
#        branch: auto/clang-tidy
#        base: dev
#    - name: Check outputs
#      if: ${{ success() }}
#      run: |
#        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
#        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"

