name: Publish Docker Compose Images

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Navitia Packages For Release"]
    branches: [release]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get branch name
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        repository: hove-io/navitia-docker-compose
    - name: install httpie dependency
      run: sudo apt update && sudo apt install -y httpie
    - name: build, create and publish images for branch [ ${{ env.BRANCH_NAME }} ]
      working-directory: builder_from_package
      run: ./build.sh -e push -o ${{secrets.access_token_github}} -t latest -b release -r -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
    - name: slack notification (the job has failed)
      if: failure()
      run: |
          echo '{"text":":warning: Navitia Github Actions: publish_docker_compose_images failed ! (https://github.com/hove-io/navitia/actions?query=workflow%3A%22Publish+Docker+Compose+Images%22)"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}

